services:
  - type: web
    name: ninera-virtual
    env: python
    plan: starter
    buildCommand: |
      pip install --upgrade pip
      pip install -r entrenamiento_ni単eravirtual2/requirements.txt
      python entrenamiento_ni単eravirtual2/ninera_virtual/manage.py collectstatic --noinput
    startCommand: gunicorn ninera_virtual.wsgi:application --chdir entrenamiento_ni単eravirtual2/ninera_virtual
    postDeployCommand: python entrenamiento_ni単eravirtual2/ninera_virtual/manage.py migrate
    envVars:
      - key: DJANGO_DEBUG
        value: "False"
      - key: DJANGO_SECRET_KEY
        generateValue: true
      - key: DATABASE_URL
        fromDatabase:
          name: ninera-virtual-db
          property: connectionString
      - key: PYTHON_VERSION
        value: 3.12.2
      - key: WEB_CONCURRENCY
        value: "2"
databases:
  - name: ninera-virtual-db
    plan: free
